name: CI on Push and Pull Request

on: 
  push:
    paths-ignore:
      - '**/*.md'
      - '*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '*.md'

jobs:
  
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
        
    - name: Install dependencies
      run: nuget restore XamFormsGithubActions/XamFormsGithubActions.NoTest.sln

    - name: Android Build
      run: dotnet build XamFormsGithubActions/App1/App1.Android/App1.Android.csproj -t:clean -p:Configuration=GitHubActions
        
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: nuget restore XamFormsGithubActions/XamFormsGithubActions.NoTest.sln
          
    - name: iOS
      run: dotnet build XamFormsGithubActions/App1/App1.iOS/App1.iOS.csproj -t:clean -p:Configuration=GitHubActions -p:Platform=iPhone

  analyze:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup dotnet for Analyze
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.x'

    # Run NuGet restore for the solution at repo root
    - name: Run NuGet restore
      run: dotnet restore

    # Run code analysis for the solution at repo root
    - name: Run .NET Code Analysis
      uses: dotnet/code-analysis@main
      id: code-analysis
      with:
        build-breaking: false

    - name: Install Reviewdog
      uses: reviewdog/action-setup@v1

    - name: Check reviewdog version
      run: reviewdog -version

#    - name: Execute custom code analysis
#      run: |
#        dotnet build XamFormsGithubActions/App1.Test/App1.Test.csproj  /p:Configuration=Release
#        dotnet run --no-build --project CustomRules/Rules.cs -- --output results.xml

    - name: Run Reviewdog for custom analysis
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        reviewdog -reporter=github-pr-check -level=error < results.xml
